server:
  port: 8081

spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/store?useTimezone=true&serverTimezone=America/Sao_Paulo'
    username: 'root'
    password: 'root'
    initialization-mode: always
    hikari:
      minimum-idle: 5
      maximum-pool-size: 4
      idle-timeout: 30000
      max-lifetime: 2000000
      connection-timeout: 30000
      pool-name: 'stockManagement-store'

  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate.show_sql: true
      hibernate.format_sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true